### PR TITLE
Global Monitoring Inventory

### PR DESCRIPTION
**Pull request by iguitton**
Published the InventoryFunctions bash and PowerShell scripts which report the number of monitored systems

### CODE REVIEW

**Comment by iguitton** [comment]
Published the InventoryFunctions bash and PowerShell scripts which report the number of monitored system

**Comment by Arif-sentry** [comment]
The PowerShell InventoryFunctions.ps1 is empty ...

**Comment by iguitton** [comment]
> 
> 
> The PowerShell InventoryFunctions.ps1 is empty ...

It is not @Arif-sentry :

image

**Comment by Arif-sentry** [comment]
@iguitton  the size of the file is 0
image

https://github.com/sentrysoftware/scripting/pull/1/files

**Pull request closed without merging**
